### PR TITLE
Added CSS for tab titles (Fixes #130)

### LINKED ISSUE #130: (GitHub News Feed Filter) The script's tab titles (Actions, Repositories, Users) appear tiled vertically after today's GitHub site update
Using GNFF 8.2.2 with Tampermonkey 4.6 in Chrome 66/Firefox 60 (tested in a new profile too).

The issue is that the script's tab titles (Actions, Repositories, Users) appear tiled vertically after today's GitHub site update (i.e. [the updated search bar](https://twitter.com/github/status/999706528373493766) I think)

Here is a screenshot from FF:

There's no error in Browser Console.
Unfortunately I couldn't find how to fix this.

### PR DESCRIPTION
**Pull request by darkred**
Added removed CSS for tab titles (Fixes #130)

Screenshot:

### CODE REVIEW

**Comment by darkred** [comment]
The problem is that I'm not very experienced with CSS, but I'll try to make it the same.

**Comment by jerone** [comment]
[**@darkred**](https://github.com/darkred) commented on [May 28, 2018, 3:52 PM GMT+2](https://github.com/jerone/UserScripts/pull/132#issuecomment-392533026 "2018-05-28T13:52:25Z - Replied by Github Reply Comments"):
> The thing is, unfortunately I'm not very familiar with CSS, but I'll try to make it the same.

And what if you use their classes...

**Comment by darkred** [comment]
I think it's ok now: 🙂

**Comment by darkred** [comment]
I corrected the screenshot: the bottom-bottom is actually orange (one of the styles I had kept enabled, was turning it blue)

**Comment by jerone** [comment]
Hi @darkred, I went with another [solution](https://github.com/jerone/UserScripts/commit/e123029c5dbc5882c8a27988ef1ef99d7871ccc4). I really value your input, it's the only reason I keep this script active 😄

**Comment by darkred** [comment]
Thanks a lot for taking the time to fix this properly! I'm glad for all 🙂

**Pull request closed without merging**
