### PR TITLE
Fixed issues after Github site update

### PR DESCRIPTION
**Pull request by jerone**
Fixes https://github.com/jerone/UserScripts/issues/68

### CODE REVIEW

**Comment by jerone** [comment]
@darkred This PR contains a fix for your issue and other changes to GitHub new changes. I was hoping you could give this version a try to confirm that the fix works.

**Comment by darkred** [comment]
Yes it's working ok now. 
Just one thing: the filters now appears in a table which has borders screenshot
I'd prefer [the previous version](https://camo.githubusercontent.com/6db28284f7d267607f57f7fb83f5b41c5bf8203d/687474703a2f2f692e696d6775722e636f6d2f465037696641612e6a7067) where there were no borders at all (or at least no borders between rows)

**Comment by jerone** [comment]
> Yes, it's working ok now.

Yeah thanks for testing :+1: 

> Just one thing: [...]

I removed the previous theme because of GitHub removing it from every elements and switching to the current theme. Personally I prefer the new one, but I just want to precede GitHub when they remove the theme all together with all these updates to the GitHub site.

Just did a commit testing a design with arrows...
2015-08-12 23_26_53-github

Not sure yet about the best solution... will try your suggestion soon.

**Comment by jerone** [comment]
Reminder for myself; 
* looks like comments on PR aren't counted as PR
* created tag aren't part of repo > tagged

**Comment by darkred** [comment]
> Yeah thanks for testing  
You're welcome.

> Not sure yet about the best solution... will try your suggestion soon.
Great

**Comment by jerone** [comment]
So I kind of settle on a combination of your and mine style suggestions:
2015-08-15 22_41_56-github
Besides the yellowish background color, font is now bold. I used dashed borders for sub filters, but kept the arrows, because there are also sub sub filters.

**Comment by darkred** [comment]
It's great now. Thank you.

**Comment by jerone** [comment]
@darkred Just merged this PR. Thanks for mentioning the issue, helping with debugging and testing. Mirrors should be synced very soon.

**Pull request merged**
