### PR TITLE
Added support for Packagist with Composer (fixes #89)

### LINKED ISSUE #89: (Github JSON Dependencies Linker) composer.json support
See https://getcomposer.org/, https://packagist.org/ and [Wikipedia](https://en.wikipedia.org/wiki/Composer_%28software%29).

### PR DESCRIPTION
**Pull request by jerone**
Added support for Packagist with Composer (fixes #89).

/cc @rugk Time to [test](https://github.com/jerone/UserScripts/raw/Github_JSON_Dependencies_Linker/Github_JSON_Dependencies_Linker/Github_JSON_Dependencies_Linker.user.js) ?

### CODE REVIEW

**Comment by rugk** [comment]
[Here](https://github.com/paragonie/halite/blob/master/composer.json) I can see `ext-libsodium` linked. However AFAIK ext-... actually is PHP module which cannot be found on Packagist. The same of course applies to "php" - but this is not linked currently anyway - which is good.
[Here](https://github.com/composer/composer/blob/master/composer.json) it is linked quite good.
However [here](https://github.com/sebastianbergmann/phpunit/blob/master/composer.json) and [here](https://github.com/composer/packagist/blob/master/composer.json) it does not link at all.

Generally this PR also lacks the linking to other [package linkers](https://getcomposer.org/doc/04-schema.md#package-links) like `require-dev`, `conflict`, `replace`, `provide` (although I do not know whether linking would be useful here) and `suggest`. [This file](https://github.com/Seldaek/monolog/blob/master/composer.json) is a good example with many such packages.

Also note that the composer.json [does not have to be at the root](https://getcomposer.org/doc/04-schema.md#root-package) of a project.

FYI Packagist != Composer - you can [also use composer with other sites](https://getcomposer.org/doc/01-basic-usage.md#packagist), but most people use Packagist.

**Comment by jerone** [comment]
Thanks for testing!

> Here I can see ext-libsodium linked. However AFAIK ext-... actually is PHP module which cannot be found on Packagist.

How do you want me to resolve this?

> "php" - but this is not linked anyway currently

Yeah I noticed that PHP wasn't a package and is probably used as [engine](https://docs.npmjs.com/files/package.json#engines).

> However here and here it does not link at all.

Linking does work for me...

> Generally this PR also does not pay attention on other package linkers like require-dev, conflict, replace, provide and suggest.

I can add those. Those don't seem to conflict with the already supported json package types. So I can add?:
* `require-dev`
* `conflict`
* `replace`
* `provide`
* `suggest`

> Also note that the composer.json does not have to be at the root of a project.

The script runs on every page load where the url ends with `composer.json`.

> FYI Packagist != Composer

What do you mean by this?

-----

Remember that I never have used Composer or Packagist and I'm pretty sure I never will (am a C# developer). I'm all for adding simple support for other dependency package type, but you have to provide the information needed.

**Comment by rugk** [comment]
[**@jerone**](https://github.com/jerone) commented on [9. Dez. 2015, 20:58 MEZ](https://github.com/jerone/UserScripts/pull/90#issuecomment-163373061 "2015-12-09T19:58:30Z - Replied by Github Comment Enhancer"):
> > Here I can see ext-libsodium linked. However AFAIK ext-... actually is PHP module which cannot be found on Packagist.
> 
> How do you want me to resolve this?

Possibly exclude all packages starting with `ext-`.

> 
> > "php" - but this is not linked anyway currently
> 
> Yeah I noticed that PHP wasn't a package and is probably used as [engine](https://docs.npmjs.com/files/package.json#engines).

Yeah...
and now I also found a list of these "special cases": https://getcomposer.org/doc/02-libraries.md#platform-packages
So this are the packages you may want to exclude.

> 
> > However here and here it does not link at all.
> 
> Linking does work for me...

Correct. Just tested it again and it works.

> 
> > Generally this PR also does not pay attention on other package linkers like require-dev, conflict, replace, provide and suggest.
> 
> I can add those. Those don't seem to conflict with the already supported json package types. So I can add?:
> 
> *   `require-dev`
> *   `conflict`
> *   `replace`
> *   `provide`
> *   `suggest`

Yes, looks good.

> 
> > Also note that the composer.json does not have to be at the root of a project.
> 
> The script runs on every page load where the url ends with `composer.json`.
> 
> > FYI Packagist != Composer
> 
> What do you mean by this?

`Packagist <> Composer`
I just visualized the difference between PAckagist and Composer. :wink: (see my link above)

> Remember that I never have used Composer or Packagist and I'm pretty sure I never will (am a C# developer). I'm all for adding simple support for other dependency package type, but you have to provide the information needed.

I'll do what I can. But there are pretty much PHP developers outside there, which also use composer... :smiley: 
And I think the docs of Composer already help a lot.

**Comment by rugk** [comment]
Any news on this on?

**Comment by jerone** [comment]
Sorry @rugk, I've got no real interest to update this PR. If you still want this feature you can fork this PR, send me a completed PR and I'll consider it again.

**Pull request closed without merging**
