### PR TITLE
Adds support for byond .dmi files to the github image viewer.

### PR DESCRIPTION
**Pull request by Boggart**
Adds previewing support for byond .dmi files. (They're really just PNGs with some metadata.)

### CODE REVIEW

**Comment by jerone** [comment]
Do you have a test case I can test...

**Comment by jerone** [comment]
Something like: https://github.com/DuncanFairley/Dungeon-Master/blob/master/icon.dmi ???

If that's the case I'm not going to merge this PR, because you probably have a plugin running that can open that file in your browser, while out-of-the-box this isn't supported for everyone else. Sorry.

**Comment by Boggart** [comment]
I'd thought that github supported viewing them natively but it seems I was wrong, that was an image hosting site that apparently sent the data as a regular png despite the extension.

Previewing the files on hover does work, but if you click on them github doesn't serve it as an image.
https://github.com/tgstation/-tg-station/tree/master/icons

I'll close this for now and re-open it if github gets support for dmi files in the future.

**Comment by jerone** [comment]
You could [contact GitHub](https://github.com/contact) and ask for `.dmi` file support. They mostly respond quickly.

Still thanks for using.

**Comment by Boggart** [comment]
I've contacted them about supporting it, thank you for writing these useful userscripts.

**Pull request closed without merging**
